# Ex1 - Getting and knowing your Data

### Step 1. Go to https://www.kaggle.com/openfoodfacts/world-food-facts/data

###  Step 2. Download the dataset to your computer and unzip it.

In [0]:
import pandas as pd
import numpy as np

** Sample code below to acess the file uploaded in google drive. 
and then convert it to pandas dataframe.

In [0]:
# Code to read csv file into Colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:
link = 'https://drive.google.com/open?id=1XYnJKaEUvnVE5-fQwH28WpnCGqxDLn4Y'      # The shareable link picked up of file from google drive

In [0]:
link2 ='https://drive.google.com/open?id=1Mrsv44dR7AzLAGcH6wRknn_p2vhJoJXi'

In [0]:
fluff, id = link.split('=')
print (id)                         # Verify that you have everything after '='

1XYnJKaEUvnVE5-fQwH28WpnCGqxDLn4Y

In [6]:
fluff,id=link2.split('=')
print(id)

1Mrsv44dR7AzLAGcH6wRknn_p2vhJoJXi

In [0]:
downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('Euro_2012_stats_TEAM.csv')  
df3 = pd.read_csv('Euro_2012_stats_TEAM.csv')
# Dataset is now stored in a Pandas Dataframe

In [0]:
df3.head()

             Team  Goals  Shots on target  ...  Subs on Subs off Players Used
0         Croatia      4               13  ...        9        9           16
1  Czech Republic      4               13  ...       11       11           19
2         Denmark      4               10  ...        7        7           15
3         England      5               11  ...       11       11           16
4          France      3               22  ...       11       11           19

[5 rows x 35 columns]

In [9]:
downloaded=drive.CreateFile({'id':id})
downloaded.GetContentFile('en.openfoodfacts.org.products.tsv')
food=pd.read_csv('en.openfoodfacts.org.products.tsv',sep='\t')
food.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

    code  ... water-hardness_100g
0   3087  ...                 NaN
1   4530  ...                 NaN
2   4559  ...                 NaN
3  16087  ...                 NaN
4  16094  ...                 NaN

[5 rows x 163 columns]

### Step 3. Use the tsv file and assign it to a dataframe called food

In [0]:
#food = pd.read_csv('~/Desktop/en.openfoodfacts.org.products.tsv', sep='\t')

### Step 4. See the first 5 entries

In [10]:
food.head()

    code  ... water-hardness_100g
0   3087  ...                 NaN
1   4530  ...                 NaN
2   4559  ...                 NaN
3  16087  ...                 NaN
4  16094  ...                 NaN

[5 rows x 163 columns]

### Step 5. What is the number of observations in the dataset?

In [11]:
food.shape #will give you both (observations/rows, columns)

(356027, 163)

In [12]:
food.shape[0] #will give you only the observations/rows number

356027

### Step 6. What is the number of columns in the dataset?

In [13]:
print(food.shape) #will give you both (observations/rows, columns)
print(food.shape[1]) #will give you only the columns number

#OR

food.info() #Columns: 163 entries

(356027, 163)
163
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356027 entries, 0 to 356026
Columns: 163 entries, code to water-hardness_100g
dtypes: float64(107), object(56)
memory usage: 442.8+ MB

In [26]:
food.describe()

       no_nutriments    additives_n  ...  glycemic-index_100g  water-hardness_100g
count            0.0  283867.000000  ...                  0.0                  0.0
mean             NaN       1.876851  ...                  NaN                  NaN
std              NaN       2.501022  ...                  NaN                  NaN
min              NaN       0.000000  ...                  NaN                  NaN
25%              NaN       0.000000  ...                  NaN                  NaN
50%              NaN       1.000000  ...                  NaN                  NaN
75%              NaN       3.000000  ...                  NaN                  NaN
max              NaN      30.000000  ...                  NaN                  NaN

[8 rows x 107 columns]

### Step 7. Print the name of all the columns.

In [0]:
food.columns

Index([u'code', u'url', u'creator', u'created_t', u'created_datetime',
       u'last_modified_t', u'last_modified_datetime', u'product_name',
       u'generic_name', u'quantity',
       ...
       u'fruits-vegetables-nuts_100g', u'fruits-vegetables-nuts-estimate_100g',
       u'collagen-meat-protein-ratio_100g', u'cocoa_100g', u'chlorophyl_100g',
       u'carbon-footprint_100g', u'nutrition-score-fr_100g',
       u'nutrition-score-uk_100g', u'glycemic-index_100g',
       u'water-hardness_100g'],
      dtype='object', length=163)

In [33]:
food.columns[:20]

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity', 'packaging', 'packaging_tags', 'brands',
       'brands_tags', 'categories', 'categories_tags', 'categories_en',
       'origins', 'origins_tags', 'manufacturing_places'],
      dtype='object')

### Step 8. What is the name of 105th column?

In [14]:
food.columns[104]

'-glucose_100g'

### Step 9. What is the type of the observations of the 105th column?

In [20]:
food.dtypes['-glucose_100g']

dtype('float64')

In [22]:
food.dtypes['-glucose_100g']

dtype('float64')

### Step 10. How is the dataset indexed?

In [27]:
food.index

RangeIndex(start=0, stop=356027, step=1)

### Step 11. What is the product name of the 19th observation?

In [35]:
food.values[18][:7]

array([18197,
       'http://world-en.openfoodfacts.org/product/0000000018197/lotus-organic-brown-jasmine-rice-unfi',
       'usda-ndb-import', 1489055652, '2017-03-09T10:34:12Z', 1489055652,
       '2017-03-09T10:34:12Z'], dtype=object)